const userActionTypes = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  GETALL_REQUEST: 'USER_GETALL_REQUEST',
  GETALL_SUCCESS: 'USER_GETALL_SUCCESS',
  GETALL_FAILURE: 'USER_GETALL_FAILURE',
};

export default userActionTypes;
